app = "knowyourports"

[build]
  image = "karldreher/knowyourports:latest"


[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

  [[services.http_checks]]
    interval = 30000
	method = "get"
	path = "/healthcheck"
	protocol = "http"
    timeout = 3000
	