
name: development-container-scan

on:
  push:
    branches: 
      - development
  schedule:
    - cron: '0 0 * * 0'

jobs:
  scan:
    runs-on: ubuntu-latest

    - name: Container image scan
      uses: Azure/container-scan@v0
      with:
         image-name: karldreher/knowyourports:development
