
name: CI

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
     - name: Container image scan
       uses: Azure/container-scan@v0
       with:
         image-name: karldreher/knowyourports
