name: Test
on:
    push:
      branches:
        - master
        - development
    # Allows running this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - name: Install Requirements
          run: pip3 install -r requirements-dev.txt

        - name: Run Tests
          run: python3 -m pytest -v